#!/usr/bin/env python3
"""Generate tool-specific agent instruction files from AGENTS.md.

Each coding tool looks for instructions in a different location:
- Claude Code / OpenAI Codex: AGENTS.md (the master copy)
- GitHub Copilot (VS Code/JetBrains): .github/copilot-instructions.md

This script reads AGENTS.md, appends project conventions, and writes
the tool-specific files. Run via: just sync-agent-docs
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AGENTS_MD = REPO_ROOT / "AGENTS.md"
COPILOT_MD = REPO_ROOT / ".github" / "copilot-instructions.md"

COPILOT_HEADER = (
    "<!-- GENERATED FROM AGENTS.md — do not edit this file directly."
    " Run: just sync-agent-docs -->\n\n"
)

PROJECT_CONVENTIONS = """
## Project conventions

- Schema source of truth: `schema/bsdbng.yaml`
- Generated Pydantic models: `src/bsdbng/datamodel/bsdbng_pydantic.py` (do not edit)
- Load YAML via Pydantic: `from bsdbng.datamodel import Study`
- Source code in `src/bsdbng/`, tests in `tests/`
- File types: CSV (input), YAML (output/schema), Python (code), JSON (logs)
- No DuckDB, no Parquet, no Jupyter notebooks
- No sentinel values — if data is missing, use `null`
- Do not hardcode file paths — use `from bsdbng.paths import ...`
- Do not commit generated output files
"""


def main() -> None:
    agents_content = AGENTS_MD.read_text()
    copilot_content = COPILOT_HEADER + agents_content + PROJECT_CONVENTIONS
    COPILOT_MD.write_text(copilot_content)
    print(f"wrote {COPILOT_MD}")


if __name__ == "__main__":
    main()
